[package]
name = "rust-actix-sqlx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0" }
chrono = { version = "0.4", features = ["serde"] }
num-traits = { version = "0.2.14" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sqlx = { version = "0.5", features = ["chrono", "decimal", "postgres", "runtime-actix-rustls", "uuid"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] } # version blocked by sqlx

