source "https://rubygems.org"

ruby "3.2.2"

gem "bootsnap", require: false
gem "jbuilder"
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
